[2022-06-20 04:02:14,686] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 4_5_op_kwargs_context_pythonop.get_data scheduled__2022-06-19T00:00:00+00:00 [queued]>
[2022-06-20 04:02:14,698] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 4_5_op_kwargs_context_pythonop.get_data scheduled__2022-06-19T00:00:00+00:00 [queued]>
[2022-06-20 04:02:14,703] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 04:02:14,709] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-20 04:02:14,714] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 04:02:14,740] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_data> on 2022-06-19 00:00:00+00:00
[2022-06-20 04:02:14,753] {standard_task_runner.py:52} INFO - Started process 80 to run task
[2022-06-20 04:02:14,762] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', '4_5_op_kwargs_context_pythonop', 'get_data', 'scheduled__2022-06-19T00:00:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/chapter04/4_5_op_kwargs_context_variable_pythonop.py', '--cfg-path', '/tmp/tmpyu4bz3f_', '--error-file', '/tmp/tmpkgpdtys8']
[2022-06-20 04:02:14,765] {standard_task_runner.py:80} INFO - Job 43: Subtask get_data
[2022-06-20 04:02:14,893] {task_command.py:369} INFO - Running <TaskInstance: 4_5_op_kwargs_context_pythonop.get_data scheduled__2022-06-19T00:00:00+00:00 [running]> on host 69ff35f06aa7
[2022-06-20 04:02:14,948] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-06-20 04:02:15,045] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=4_5_op_kwargs_context_pythonop
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2022-06-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-19T00:00:00+00:00
[2022-06-20 04:02:45,267] {python.py:173} INFO - Done. Returned value was: None
[2022-06-20 04:02:45,289] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=4_5_op_kwargs_context_pythonop, task_id=get_data, execution_date=20220619T000000, start_date=20220620T040214, end_date=20220620T040245
[2022-06-20 04:02:45,363] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-20 04:02:45,398] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
