[2022-06-13 19:10:44,946] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: listing_4_05.get_data scheduled__2022-06-13T18:00:00+00:00 [queued]>
[2022-06-13 19:10:45,016] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: listing_4_05.get_data scheduled__2022-06-13T18:00:00+00:00 [queued]>
[2022-06-13 19:10:45,018] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-13 19:10:45,020] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-13 19:10:45,024] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-13 19:10:45,062] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_data> on 2022-06-13 18:00:00+00:00
[2022-06-13 19:10:45,070] {standard_task_runner.py:52} INFO - Started process 39724 to run task
[2022-06-13 19:10:45,077] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'listing_4_05', 'get_data', 'scheduled__2022-06-13T18:00:00+00:00', '--job-id', '133', '--raw', '--subdir', 'DAGS_FOLDER/listing_4_5.py', '--cfg-path', '/tmp/tmp9c88uxrw', '--error-file', '/tmp/tmp8fmw92by']
[2022-06-13 19:10:45,082] {standard_task_runner.py:80} INFO - Job 133: Subtask get_data
[2022-06-13 19:10:45,200] {task_command.py:369} INFO - Running <TaskInstance: listing_4_05.get_data scheduled__2022-06-13T18:00:00+00:00 [running]> on host 48de8cc79e8d
[2022-06-13 19:10:45,370] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=listing_4_05
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2022-06-13T18:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-13T18:00:00+00:00
[2022-06-13 19:10:45,378] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-06-13 19:11:23,073] {python.py:173} INFO - Done. Returned value was: None
[2022-06-13 19:11:23,086] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=listing_4_05, task_id=get_data, execution_date=20220613T180000, start_date=20220613T191044, end_date=20220613T191123
[2022-06-13 19:11:23,146] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-13 19:11:23,172] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
